[package]
name = "stackyzdev/goodsignal"
description = "A fast Signal class implementation that has full feature parity with Roblox' RBXScriptSignal. Modified to use deferred signal behavior instead of immediate mode."
version = "0.3.2"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# None :)
